// <auto-generated />
using FruitsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FruitsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("FruitsAPI.Models.FavoriteFruits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FruitColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FruitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FavoriteFruits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FruitColor = "Orange",
                            FruitName = "Orange"
                        },
                        new
                        {
                            Id = 2,
                            FruitColor = "Green",
                            FruitName = "PawPaw"
                        },
                        new
                        {
                            Id = 3,
                            FruitColor = "Red",
                            FruitName = "Strawberry"
                        },
                        new
                        {
                            Id = 4,
                            FruitColor = "Green",
                            FruitName = "Mango"
                        },
                        new
                        {
                            Id = 5,
                            FruitColor = "Yellow",
                            FruitName = "Pineapple"
                        },
                        new
                        {
                            Id = 6,
                            FruitColor = "Green",
                            FruitName = "Apple"
                        },
                        new
                        {
                            Id = 7,
                            FruitColor = "Green",
                            FruitName = "Watermelon"
                        },
                        new
                        {
                            Id = 8,
                            FruitColor = "Yellow",
                            FruitName = "Banana"
                        },
                        new
                        {
                            Id = 9,
                            FruitColor = "Green",
                            FruitName = "Avocado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
